pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@github.com:romaswe/steam-inventory-checker.git
          - cd RepoName.git
          - git push --mirror git@github.com:romaswe/steam-inventory-checker.git